INSERT INTO tb_musicas (nome, categoria) VALUES ('Deus é Deus', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Grande é O Senhor', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Tua é a glória', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Consagração', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Ao Único', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Sei que foi pago um alto preço', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Nada Além do Sangue', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Aclame ao Senhor', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Reina sobre Mim', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Digno é O Senhor', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Aos pés da cruz', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Digno de glória', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Poderoso Deus', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Eu Navegarei', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Tu és Soberano sobre a terra', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Por tudo que tens feito', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Meu Respirar', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Quão grande', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Lindo és', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Perto Quero Estar', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Santo Espírito', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Tua graça me basta', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Santo é', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Sopra Espírito', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Quebrantado coração', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Eu me rendo', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Sempre fiel', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Ressussita-me', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Para sempre Te adorarei', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Em Espírito, em verdade', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Casa do Pai', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Creio Que Tu És a Cura', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Espírito Santo', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Oh quão lindo Esse nome é', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Como o rei Davi', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Deus de Promessas', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Mais que uma voz', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Corpo e família', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Bom estarmos aqui louvando a Deus', 'ADORACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Eu marquei um encontro com Deus', 'ADORACAO');

INSERT INTO tb_musicas (nome, categoria) VALUES ('Eu vou seguir com fé', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Vou Te alegrar', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Toda sorte de bênçãos', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Vem, esta é a hora', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Reina em mim', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Jesus em Tua presença', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Quebrantado', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Senhor Te quero', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Cra em mim oh Deus', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Celebrai com júbilo', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Celebrai a Cristo', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('És tu única razão', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Os anjos Te louvam', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('A alegria está no coração', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Aquele que está feliz', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Porque Ele vive', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Fico feliz', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Ele é O Leão da tribo de Judá', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('O nosso General é Cristo', 'CELEBRACAO');
INSERT INTO tb_musicas (nome, categoria) VALUES ('Quem nos separará', 'CELEBRACAO');
