--Adoração
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Deus é Deus', 'Delino Marçal', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Grande é O Senhor', 'Adhemar de Campos', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Tua é a glória', 'Rachel Novaes', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Consagração', 'Aline Barros', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Ao Único', 'Corinhos', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Sei que foi pago um alto preço', 'Asaph Borba', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Nada Além do Sangue', 'Fernandinho', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Aclame ao Senhor', 'Diante do trono', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Reina sobre Mim', 'Nívea Soares', 'ADORACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Digno é O Senhor', 'Aline Barros', 'ADORACAO', FALSE);

--Celebração
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Porque Ele vive', 'Harpa Cristã', 'CELEBRACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Fico feliz', 'Aline Barros', 'CELEBRACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Ele é O Leão da tribo de Judá', 'Corinho', 'CELEBRACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('O nosso General é Cristo', 'Adhemar de Campos', 'CELEBRACAO', FALSE);
INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Quem nos separará', 'Diante do Trono', 'CELEBRACAO', FALSE);

-- INSERT INTO tb_musicas (nome, cantor, categoria, pular_musica) VALUES ('Deus é Deus', 'Delino Marçal' , 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Grande é O Senhor', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Tua é a glória', 'ADORACAO'), FALSE;
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Consagração', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Ao Único', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Sei que foi pago um alto preço', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Nada Além do Sangue', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Aclame ao Senhor', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Reina sobre Mim', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Digno é O Senhor', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Aos pés da cruz', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Digno de glória', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Poderoso Deus', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Eu Navegarei', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Tu és Soberano sobre a terra', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Por tudo que tens feito', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Meu Respirar', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Quão grande', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Lindo és', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Perto Quero Estar', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Santo Espírito', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Tua graça me basta', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Santo é', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Sopra Espírito', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Quebrantado coração', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Eu me rendo', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Sempre fiel', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Ressussita-me', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Para sempre Te adorarei', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Em Espírito, em verdade', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Casa do Pai', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Creio Que Tu És a Cura', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Espírito Santo', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Oh quão lindo Esse nome é', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Como o rei Davi', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Deus de Promessas', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Mais que uma voz', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Corpo e família', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Bom estarmos aqui louvando a Deus', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Eu marquei um encontro com Deus', 'ADORACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Eu vou seguir com fé', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Vou Te alegrar', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Toda sorte de bênçãos', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Vem, esta é a hora', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Reina em mim', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Jesus em Tua presença', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Quebrantado', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Senhor Te quero', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Cra em mim oh Deus', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Celebrai com júbilo', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Celebrai a Cristo', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('És tu única razão', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Os anjos Te louvam', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('A alegria está no coração', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Aquele que está feliz', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Porque Ele vive', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Fico feliz', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Ele é O Leão da tribo de Judá', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('O nosso General é Cristo', 'CELEBRACAO', FALSE);
-- INSERT INTO tb_musicas (nome, categoria, pular_musica) VALUES ('Quem nos separará', 'CELEBRACAO', FALSE);